// src/application/vue/components/App.vue
<template>
  <div class="todoapp">
    <header>
      <h1>todo list</h1>
      <todo-input :viewModel="viewModel.todoInputViewModel"></todo-input>
      <input
        id="toggle-all"
        class="toggle-all"
        type="checkbox"
        @change="toggleAll"
        :checked="viewModel.showToggleAllActive"
      />
      <label
        for="toggle-all"
      ></label>
    </header>
    <div class="main">
      <todo-list :viewModel="viewModel.todoListViewModel"></todo-list>
      <todo-footer :viewModel="viewModel.todoFooterViewModel"></todo-footer>
    </div>
  </div>
</template>

<script lang="ts">
import { container } from "../inversify.config";
import Vue from 'vue';
import Component from "vue-class-component";
import TodoInput from "./TodoInput.vue";
import TodoList from "./TodoList.vue";
import TodoFooter from "./TodoFooter.vue";
import { TYPES } from '../../../types';
import { IAppViewModel } from '../../../presentation/AppViewModel';
import { Observer } from 'mobx-vue';

const appViewModel = container.get<IAppViewModel>(TYPES.AppViewModel);

console.log(appViewModel);

@Observer
@Component({
  components: {
    "todo-input": TodoInput,
    "todo-list": TodoList,
    "todo-footer": TodoFooter
  }
})
export default class App extends Vue {

  private viewModel: IAppViewModel = appViewModel

  toggleAll() {
    this.viewModel.toggleAll();
  }
}
</script>

// src/application/react/components/App.tsx
import { observer } from 'mobx-react';
import * as React from 'react';
import { IAppViewModel } from '../../../presentation/AppViewModel';
import { IViewFor } from '../IViewFor';
import TodoFooter from './TodoFooter';
import TodoInput from './TodoInput';
import TodoList from './TodoList';

@observer
export default class App extends React.Component<IViewFor<IAppViewModel>> {
  public toggleAll = () => {
    this.props.viewModel.toggleAll();
  }

  public render() {
    return (
      <div className="todoapp">
        <header>
          <h1>todo list</h1>
          <TodoInput viewModel={this.props.viewModel.todoInputViewModel} />
          <input
            id="toggle-all"
            className="toggle-all"
            type="checkbox"
            onChange={this.toggleAll}
            checked={this.props.viewModel.showToggleAllActive}
          />
          <label
            htmlFor="toggle-all"
          />
        </header>
        <div className="main">
          <TodoList viewModel={this.props.viewModel.todoListViewModel} />
          <TodoFooter viewModel={this.props.viewModel.todoFooterViewModel} />
        </div>
      </div>
    );
  }
}
