// src/application/vue/components/TodoList.vue
<template>
  <div class="todo-list">
    <todo-item
      v-for="vm in viewModel.todoItemViewModels"
      :key="vm.todoItem.uuid"
      :viewModel="vm"
    ></todo-item>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import { observer } from 'mobx-vue';
import Component from 'vue-class-component';
import TodoItem from './TodoItem.vue';
import { ITodoListViewModel } from '../../../presentation/TodoListViewModel';

@observer
@Component({
  components: {
    "todo-item": TodoItem
  },
  props: {
    viewModel: {
      type: Object as () => ITodoListViewModel
    }
  }
})
export default class TodoList extends Vue {

}
</script>

// src/application/react/components/TodoList.tsx
import { observer } from 'mobx-react';
import * as React from 'react';
import { ITodoListViewModel } from '../../../presentation/TodoListViewModel';
import { IViewFor } from '../IViewFor';
import TodoItem from './TodoItem';

@observer
export default class TodoList extends React.Component<IViewFor<ITodoListViewModel>> {
  public renderTodoList() {
    return this.props.viewModel.todoItemViewModels.map((todoViewModel) => (
      <TodoItem viewModel={todoViewModel} key={todoViewModel.todoItem.uuid} />
    ));
  }

  public render() {
    return (
      <div className="todo-list">
        {this.renderTodoList()}
      </div>
    );
  }
}
