// src/application/vue/components/TodoItem.vue
<template>
  <li :class="{ completed: viewModel.todoItem.completed, editing: viewModel.editing }">
    <div class="view">
      <input
        class="toggle"
        type="checkbox"
        :checked="viewModel.todoItem.completed"
        @change="toggleTodo"
      />
      <label @dblclick="handleEdit">
        {{viewModel.todoItem.title}}
      </label>
      <button class="destroy" @click="handleDestroy" />
    </div>
    <input
      class="edit"
      v-model="viewModel.editText"
      @blur="handleBlur"
      @change="$emit('handleChange', $event.target.value)"
      @keydown.enter="handleComplete"
    />
  </li>
</template>
<script lang="ts">
import Vue from 'vue'
import { observer } from 'mobx-vue';
import Component from 'vue-class-component';
import classnames from "classnames";
import { ITodoItemViewModel } from '../../../presentation/TodoItemViewModel';

@observer
@Component({
   props: {
    viewModel: {
      type: Object as () => ITodoItemViewModel
    }
  }
})
export default class TodoItem extends Vue {
  toggleTodo() {
    this.$props.viewModel.toggleTodo()
  }

  handleBlur() {
    this.$props.viewModel.updateTodo()
  }

  handleChange(value: string) {
    this.$props.viewModel.updateEditTxt(value);
  }

  handleComplete() {
    this.$props.viewModel.updateTodo();
  }

  handleDestroy() {
    this.$props.viewModel.deleteTodo();
  }

  handleEdit() {
    this.$props.viewModel.toggleEditing(true);
  }
}
</script>

// src/components/todoItem/TodoItem.tsx
import * as React from 'react';
import { observer } from 'mobx-react';
import classNames from 'classnames';
import { ITodoItemViewModel } from './TodoItemViewModel';
import IViewModel from '../../IViewModel';

const ENTER_KEY = 13;

@observer
export default class TodoItem extends React.Component<IViewModel<ITodoItemViewModel>> {
  handleEdit = () => {
    this.props.vm.toggleEditing(true);
  }

  handleBlur = () => {
    this.props.vm.updateTodo();
  }
  handleDestroy = () => {
    this.props.vm.deleteTodo();
  }

  handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    this.props.vm.updateEditTxt(e.target.value)
  }

  handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.keyCode !== ENTER_KEY) {
      return;
    }
    e.preventDefault();
    this.props.vm.updateTodo();
  }

  render() {
    const { vm } = this.props;
    const { completed, title } = vm.todoItem;
    return (
      <li className={classNames({
        completed,
        editing: vm.editing
      })}>
        <div className="view">
          <input
            className="toggle"
            type="checkbox"
            checked={completed}
            onChange={() => vm.toggleTodo()}
          />
          <label onDoubleClick={this.handleEdit}>
            {title}
          </label>
          <button className="destroy" onClick={this.handleDestroy} />
        </div>
        <input
          ref="editField"
          className="edit"
          value={vm.editText}
          onBlur={this.handleBlur}
          onChange={this.handleChange}
          onKeyDown={this.handleKeyDown}
        />
      </li>
    );
  }
};
