// src/application/vue/components/TodoList.vue
<template>
  <div class="todo-list">
    <todo-item
      v-for="vm in viewModel.todoItemViewModels"
      :key="vm.todoItem.uuid"
      :viewModel="vm"
    ></todo-item>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import { observer } from 'mobx-vue';
import Component from 'vue-class-component';
import TodoItem from './TodoItem.vue';
import { ITodoListViewModel } from '../../../presentation/TodoListViewModel';

@observer
@Component({
  components: {
    "todo-item": TodoItem
  },
  props: {
    viewModel: {
      type: Object as () => ITodoListViewModel
    }
  }
})
export default class TodoList extends Vue {

}
</script>

// src/components/todoList/TodoList.tsx
import * as React from 'react';
import { observer } from 'mobx-react';
import TodoItem from '../todoItem/TodoItem';
import { ITodoListViewModel } from './TodoListViewModel';
import IViewModel from '../../IViewModel';

@observer
export default class TodoList extends React.Component<IViewModel<ITodoListViewModel>> {
  renderTodoList() {
    const { todoVms } = this.props.vm;
    return todoVms.map((todoVm) => (
      <TodoItem vm={todoVm} key={todoVm.todoItem.uuid} />
    ));
  }

  render() {
    return (
      <div className="todo-list">
        {this.renderTodoList()}
      </div>
    );
  }
}
