// src/application/vue/components/TodoFooter.vue
<template>
  <footer class="footer">
    <span class="todo-count">
      <strong>{{viewModel.count}}</strong> item{{viewModel.count > 1 ? 's': ''}}
    </span>
    <ul class="filters">
      <li v-for="filter in filters" :key="filter.text" >
        <a @click="handleFilterChange(filter.value)" :class="{ selected: filter.value === viewModel.filter }" >
          {{filter.text}}
        </a>
      </li>
    </ul>
    <button
      class="clear-completed"
      @click="handleClearCompleted"
      v-show="viewModel.showClearBtn"
    >
      Clear completed
    </button>
  </footer>
</template>

<script lang="ts">
import Vue from 'vue'
import { observer } from 'mobx-vue';
import Component from 'vue-class-component';
import { ITodoFooterViewModel } from '../../../presentation/TodoFooterViewModel';
import { Filter } from '../../../core/store/todoStore';

@observer
@Component({
  props: {
    viewModel: {
      type: Object as () => ITodoFooterViewModel
    }
  }
})
export default class TodoFooter extends Vue {
  filters = [{
    value: Filter.ALL,
    text: "All"
  }, {
    value: Filter.ACTIVE,
    text: "Active",
  }, {
    value: Filter.COMPLETED,
    text: "Completed"
  }]

  handleFilterChange(filter: Filter) {
    this.$props.viewModel.handleFilterChanged(filter)
  }

  handleClearCompleted() {
    this.$props.viewModel.clearCompleted();
  }
}
</script>

// src/views/react/TodoFooter.tsx
import classNames from 'classnames';
import { observer } from 'mobx-react';
import * as React from 'react';
import { ITodoFooterViewModel } from '../../presentation/TodoFooterViewModel';
import { IViewFor } from './IViewFor';
import { Filter } from '../../core/store/todoStore';

@observer
export default class TodoFooter extends React.Component<IViewFor<ITodoFooterViewModel>> {
  public handleSelect = (e: React.MouseEvent<HTMLAnchorElement>, filter: Filter) => {
    e.preventDefault();
    this.props.viewModel.handleFilterChanged(filter);
  }

  public renderItem(filter: Filter, text: string) {
    const selected = this.props.viewModel.filter === filter;
    const clx = classNames({ selected });
    return (
      <li>
        <a onClick={(e) => this.handleSelect(e, filter)} className={clx} >
          {text}
        </a>
      </li>
    );
  }

  public renderClearBtn() {
    if (this.props.viewModel.showClearBtn) {
      return (
        <button
          className="clear-completed"
          onClick={() => this.props.viewModel.clearCompleted()}
        >
          Clear completed
        </button>
      )
    }
    return null;
  }

  public render() {
    return (
      <footer className="footer">
          <span className="todo-count">
            <strong>{this.props.viewModel.count}</strong> item{this.props.viewModel.count > 1 ? 's': ''}
          </span>
          <ul className="filters">
            {this.renderItem(Filter.ALL, 'All')}
            {this.renderItem(Filter.ACTIVE, 'Active')}
            {this.renderItem(Filter.COMPLETED, 'Completed')}
          </ul>
          {this.renderClearBtn()}
        </footer>
    )
  }
}
