// src/App.tsx
import * as React from 'react';
import { observer } from 'mobx-react';
import TodoList from './components/todoList/TodoList';
import TodoInput from './components/todoInput/TodoInput';
import TodoFooter from './components/todoFooter/TodoFooter';
import { IAppViewModel } from './AppViewModel';
import IViewModel from './IViewModel';

@observer
export default class App extends React.Component<IViewModel<IAppViewModel>> {
  toggleAll = () => {
    this.props.vm.toggleAll();
  }

  render() {
    const { vm } = this.props;
    return (
      <div className="todoapp">
        <header>
          <h1>todos</h1>
          <TodoInput vm={vm.todoInputVm} />
          <input
            id="toggle-all"
            className="toggle-all"
            type="checkbox"
            onChange={this.toggleAll}
            checked={vm.toggleAllActive}
          />
          <label
            htmlFor="toggle-all"
          />
        </header>
        <div className="main">
          <TodoList vm={vm.todoListVm} />
          <TodoFooter vm={vm.todoFooterVm} />
        </div>
      </div>
    );
  }
}

// src/application/vue/components/App.vue
<template>
  <div class="todoapp">
    <header>
      <h1>todo list</h1>
      <todo-input :viewModel="viewModel.todoInputViewModel"></todo-input>
      <input
        id="toggle-all"
        class="toggle-all"
        type="checkbox"
        @change="toggleAll"
        :checked="viewModel.showToggleAllActive"
      />
      <label
        for="toggle-all"
      ></label>
    </header>
    <div class="main">
      <todo-list :viewModel="viewModel.todoListViewModel"></todo-list>
      <todo-footer :viewModel="viewModel.todoFooterViewModel"></todo-footer>
    </div>
  </div>
</template>

<script lang="ts">
import { container } from "../inversify.config";
import Vue from 'vue';
import Component from "vue-class-component";
import TodoInput from "./TodoInput.vue";
import TodoList from "./TodoList.vue";
import TodoFooter from "./TodoFooter.vue";
import { TYPES } from '../../../types';
import { IAppViewModel } from '../../../presentation/AppViewModel';
import { Observer } from 'mobx-vue';

const appViewModel = container.get<IAppViewModel>(TYPES.AppViewModel);

console.log(appViewModel);

@Observer
@Component({
  components: {
    "todo-input": TodoInput,
    "todo-list": TodoList,
    "todo-footer": TodoFooter
  }
})
export default class App extends Vue {

  private viewModel: IAppViewModel = appViewModel

  toggleAll() {
    this.viewModel.toggleAll();
  }
}
</script>
