// src/components/todoFooter/TodoFooter.tsx
import * as React from 'react';
import { observer } from 'mobx-react';
import classNames from 'classnames';
import { ITodoFooterViewModel } from './TodoFooterViewModel';
import IViewModel from '../../IViewModel';
import history from '../../common/history';

@observer
export default class TodoFooter extends React.Component<IViewModel<ITodoFooterViewModel>> {
  handleSelect = (e: React.MouseEvent<HTMLAnchorElement>, url: string) => {
    e.preventDefault();
    history.push(url);
  }

  renderItem(url: string, type: string, text: string) {
    const { vm } = this.props;
    const selected = vm.selected === type;
    const clx = classNames({ selected });
    return (
      <li>
        <a onClick={(e) => this.handleSelect(e, url)} className={clx} >
          {text}
        </a>
      </li>
    );
  }

  renderClearBtn() {
    const { vm } = this.props;
    if (vm.showClearBtn) {
      return (
        <button
          className="clear-completed"
          onClick={() => vm.clearCompleted()}
        >
          Clear completed
        </button>
      )
    }
    return null;
  }

  render() {
    const { vm } = this.props;
    return (
      <footer className="footer">
          <span className="todo-count">
            <strong>{vm.count}</strong> item{vm.count > 1 ? 's': ''}
          </span>
          <ul className="filters">
            {this.renderItem('#/', 'ALL', 'All')}
            {this.renderItem('#/active', 'ACTIVE', 'Active')}
            {this.renderItem('#/completed', 'COMPLETED', 'Completed')}
          </ul>
          {this.renderClearBtn()}
        </footer>
    )
  }
}

// src/application/vue/components/TodoFooter.vue
<template>
  <footer class="footer">
    <span class="todo-count">
      <strong>{{viewModel.count}}</strong> item{{viewModel.count > 1 ? 's': ''}}
    </span>
    <ul class="filters">
      <li v-for="filter in filters" :key="filter.text" >
        <a @click="handleFilterChange(filter.value)" :class="{ selected: filter.value === viewModel.filter }" >
          {{filter.text}}
        </a>
      </li>
    </ul>
    <button
      class="clear-completed"
      @click="handleClearCompleted"
      v-show="viewModel.showClearBtn"
    >
      Clear completed
    </button>
  </footer>
</template>

<script lang="ts">
import Vue from 'vue'
import { observer } from 'mobx-vue';
import Component from 'vue-class-component';
import { ITodoFooterViewModel } from '../../../presentation/TodoFooterViewModel';
import { Filter } from '../../../core/store/todoStore';

@observer
@Component({
  props: {
    viewModel: {
      type: Object as () => ITodoFooterViewModel
    }
  }
})
export default class TodoFooter extends Vue {
  filters = [{
    value: Filter.ALL,
    text: "All"
  }, {
    value: Filter.ACTIVE,
    text: "Active",
  }, {
    value: Filter.COMPLETED,
    text: "Completed"
  }]

  handleFilterChange(filter: Filter) {
    this.$props.viewModel.handleFilterChanged(filter)
  }

  handleClearCompleted() {
    this.$props.viewModel.clearCompleted();
  }
}
</script>
