// src/application/vue/components/TodoInput.vue
<template>
  <input
    class="new-todo"
    v-model="viewModel.input"
    placeholder="What need to be done?"
    @change="$emit('handleInputChange', $event.target.value)"
    @keydown.enter="handelComplete"
  />
</template>

<script lang="ts">
import Vue from 'vue'
import Component from 'vue-class-component';
import { observer } from 'mobx-vue';
import { ITodoInputViewModel } from "../../../presentation/TodoInputViewModel";

@observer
@Component({
  props: {
    viewModel: {
      type: Object as () => ITodoInputViewModel
    }
  }
})
export default class TodoInput extends Vue {
  handleInputChange(value: string) {
    this.$props.viewModel.updateInput(value)
  }

  handelComplete() {
    this.$props.viewModel.addTodo();
  }
}

</script>

// src/components/todoInput/TodoInput.tsx
import * as React from 'react';
import { observer } from 'mobx-react';
import { ITodoInputViewModel } from './TodoInputViewModel';
import IViewModel from '../../IViewModel';

const ENTER_KEY = 13;

@observer
export default class TodoInput extends React.Component<IViewModel<ITodoInputViewModel>> {
  handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    this.props.vm.updateInput(e.target.value)
  }

  handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.keyCode !== ENTER_KEY) {
      return;
    }
    e.preventDefault();
    this.props.vm.addTodo();
  }

  render() {
    const { vm } = this.props;
    return (
      <input
        className="new-todo"
        value={vm.input}
        placeholder="What need to be done?"
        onChange={this.handleInputChange}
        onKeyDown={this.handleKeyDown}
      />
    );
  }
}
